In [18]:
import torch
qkv = torch.tensor([1,1,1,1,1,1,1,1,
                    2,2,2,2,2,2,2,2,
                    3,3,3,3,3,3,3,3,
                    1,1,1,1,1,1,1,1,
                    2,2,2,2,2,2,2,2,
                    3,3,3,3,3,3,3,3,
                    1,1,1,1,1,1,1,1,
                    2,2,2,2,2,2,2,2,
                    3,3,3,3,3,3,3,3,
                    1,1,1,1,1,1,1,1,
                    2,2,2,2,2,2,2,2,
                    3,3,3,3,3,3,3,3])

In [60]:
# So, the GPTNeo code basically goes
# q,k,v,q,k,v,q,k,v...

# The NanoGPT code basically goes
# q,q,q,q,k,k,k,k,v,v,v,v
# We want to convert the qkv tensor from the first to the second

qkv.view(4, -1, 8).transpose(0, 1)#qkv.split(self.n_embd, dim=2)

tensor([[[1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1]],

        [[2, 2, 2, 2, 2, 2, 2, 2],
         [2, 2, 2, 2, 2, 2, 2, 2],
         [2, 2, 2, 2, 2, 2, 2, 2],
         [2, 2, 2, 2, 2, 2, 2, 2]],

        [[3, 3, 3, 3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3, 3, 3, 3]]])

In [19]:
qkv.reshape(8, 12)

tensor([[ 1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,
          1.0000e+00,  1.0000e+00,  1.0000e+00,  6.9100e-02,  4.0000e-03,
          1.2800e-02, -1.5450e-01],
        [ 6.6000e-03,  1.4840e-01,  2.5000e-02, -1.1090e-01,  1.2340e-01,
         -5.8700e-02,  9.0000e-02,  1.3600e-02, -1.1570e-01,  7.5700e-02,
          1.9100e-02,  1.1660e-01],
        [-4.6500e-02,  1.1580e-01,  2.2000e-02, -5.0800e-02, -9.9700e-02,
         -4.1000e-03, -5.8100e-02,  2.0900e-01, -1.3100e-02,  1.8620e-01,
          8.6000e-02, -1.2130e-01],
        [ 1.5300e-01, -1.0180e-01,  5.1000e-02, -1.5780e-01,  3.3000e-02,
         -8.5100e-02,  1.4910e-01, -9.2900e-02,  1.8680e-01, -1.8200e-02,
         -1.7950e-01, -8.6100e-02],
        [-8.3700e-02, -1.3080e-01, -1.2530e-01,  8.4400e-02,  2.0460e-01,
          6.6600e-02, -1.0880e-01, -7.1600e-02, -1.7490e-01,  2.0420e-01,
         -9.6000e-02,  2.3120e-01],
        [ 1.0370e-01, -3.4300e-02,  5.7700e-02,  9.6200e-02, -2.7200e-02,
      

In [20]:
qkv.view(-1,3).transpose(0,1)

tensor([[ 1.0000e+00,  1.0000e+00,  1.0000e+00,  4.0000e-03,  6.6000e-03,
         -1.1090e-01,  9.0000e-02,  7.5700e-02, -4.6500e-02, -5.0800e-02,
         -5.8100e-02,  1.8620e-01,  1.5300e-01, -1.5780e-01,  1.4910e-01,
         -1.8200e-02, -8.3700e-02,  8.4400e-02, -1.0880e-01,  2.0420e-01,
          1.0370e-01,  9.6200e-02, -1.5070e-01,  1.8800e-02, -2.3600e-02,
          3.9300e-02, -2.1850e-01, -9.2700e-02, -7.6600e-02,  1.2670e-01,
          7.8800e-02,  3.5200e-02],
        [ 1.0000e+00,  1.0000e+00,  1.0000e+00,  1.2800e-02,  1.4840e-01,
          1.2340e-01,  1.3600e-02,  1.9100e-02,  1.1580e-01, -9.9700e-02,
          2.0900e-01,  8.6000e-02, -1.0180e-01,  3.3000e-02, -9.2900e-02,
         -1.7950e-01, -1.3080e-01,  2.0460e-01, -7.1600e-02, -9.6000e-02,
         -3.4300e-02, -2.7200e-02,  1.2000e-01,  4.0500e-02, -1.5620e-01,
          1.6730e-01, -2.1200e-02,  1.1070e-01,  3.7100e-02,  1.5480e-01,
         -5.0400e-02, -1.2210e-01],
        [ 1.0000e+00,  1.0000e+00,  6.91

In [12]:
qkv.split(8, dim=2)

(tensor([[[-0.0219,  0.1081,  0.0137, -0.1227, -0.1748, -0.1488, -0.0723,
           -0.1397]]]),
 tensor([[[ 0.0691,  0.0040,  0.0128, -0.1545,  0.0066,  0.1484,  0.0250,
           -0.1109]]]),
 tensor([[[ 0.1234, -0.0587,  0.0900,  0.0136, -0.1157,  0.0757,  0.0191,
            0.1166]]]),
 tensor([[[-0.0465,  0.1158,  0.0220, -0.0508, -0.0997, -0.0041, -0.0581,
            0.2090]]]),
 tensor([[[-0.0131,  0.1862,  0.0860, -0.1213,  0.1530, -0.1018,  0.0510,
           -0.1578]]]),
 tensor([[[ 0.0330, -0.0851,  0.1491, -0.0929,  0.1868, -0.0182, -0.1795,
           -0.0861]]]),
 tensor([[[-0.0837, -0.1308, -0.1253,  0.0844,  0.2046,  0.0666, -0.1088,
           -0.0716]]]),
 tensor([[[-0.1749,  0.2042, -0.0960,  0.2312,  0.1037, -0.0343,  0.0577,
            0.0962]]]),
 tensor([[[-0.0272, -0.0970, -0.1507,  0.1200, -0.1456,  0.0188,  0.0405,
            0.0484]]]),
 tensor([[[-0.0236, -0.1562,  0.2102,  0.0393,  0.1673, -0.1163, -0.2185,
           -0.0212]]]),
 tensor([[[-0.1767, 